/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2022-08-05 03:46:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.java3x.dto.Java3xDTO;
import java.lang.*;
import java.util.*;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.java3x.dto.Java3xDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>RETRIEVE</title>\r\n");
      out.write("</head>\r\n");

Java3xDTO dto = new Java3xDTO();
if (session.getAttribute("dto") != null) {
	System.out.println("Initilaize session to dto");
	dto = (Java3xDTO) session.getAttribute("dto");
} else
	System.out.println("Session is empty");

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<h2>RETRIEVE RECORD</h2>\r\n");
      out.write("	<br>\r\n");
      out.write("	<form action=\"ViewController\" method=\"get\">\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>ID Number</td>\r\n");
      out.write("				<td>:</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"id\" id=\"id\"\r\n");
      out.write("					value=");
      out.print(dto.getName());
      out.write("> <select name=\"idType\"\r\n");
      out.write("					id=\"idType\">\r\n");
      out.write("						<option value=UIN>UIN</option>\r\n");
      out.write("						<option value=FIN>FIN</option>\r\n");
      out.write("						<option value=PPN>PPN</option>\r\n");
      out.write("						<option value=XIN>XIN</option>\r\n");
      out.write("				</select></td>\r\n");
      out.write("				<td></td>\r\n");
      out.write("				<td><input type=\"submit\" name=\"submit\"\r\n");
      out.write("					value=\"Retrieve Personal Data\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Name</td>\r\n");
      out.write("				<td>:</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"name\" id=\"name\"\r\n");
      out.write("					value=");
      out.print(dto.getName());
      out.write("></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Relationship to ");
      out.print(dto.getName());
      out.write("</td>\r\n");
      out.write("				<td>:</td>\r\n");
      out.write("				<td><select name=\"relation\" id=\"relation\">\r\n");
      out.write("\r\n");
      out.write("						<option value=spouse\r\n");
      out.write("							");
if (dto.getRelation() != null && dto.getRelation().equalsIgnoreCase("Husband/Wife")) {
      out.write("\r\n");
      out.write("							selected ");
}
      out.write(">Husband/Wife</option>\r\n");
      out.write("						<option value=kid\r\n");
      out.write("							");
if (dto.getRelation() != null && dto.getRelation().equalsIgnoreCase("Son/Daughter")) {
      out.write("\r\n");
      out.write("							selected>\r\n");
      out.write("							");

							}
							
      out.write("Son/Daughter\r\n");
      out.write("						</option>\r\n");
      out.write("						<option value=sibbling\r\n");
      out.write("							");
if (dto.getRelation() != null && dto.getRelation().equalsIgnoreCase("Brother/Sister")) {
      out.write("\r\n");
      out.write("							selected ");
}
      out.write(">Brother/Sister</option>\r\n");
      out.write("						<option value=parent\r\n");
      out.write("							");
if (dto.getRelation() != null && dto.getRelation().equalsIgnoreCase("Father/Mother")) {
      out.write("\r\n");
      out.write("							selected ");
}
      out.write(">Father/Mother</option>\r\n");
      out.write("				</select></td>\r\n");
      out.write("				<td>Gender :</td>\r\n");
      out.write("				<td><input type=\"radio\" name=\"gender\" id=\"gender\" value=\"male\"\r\n");
      out.write("					");
if (dto.getGender() != null && dto.getGender().equalsIgnoreCase("male")) {
      out.write("\r\n");
      out.write("					checked ");
}
      out.write(">Male <input type=\"radio\" name=\"gender\"\r\n");
      out.write("					id=\"gender\" value=\"female\"\r\n");
      out.write("					");
if (dto.getGender() != null && dto.getGender().equalsIgnoreCase("Female")) {
      out.write("\r\n");
      out.write("					checked ");
}
      out.write(">Female</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Date of Birth</td>\r\n");
      out.write("				<td>:</td>\r\n");
      out.write("				<td><input type=\"date\" name=\"dob\" id=\"dob\"\r\n");
      out.write("					value=");
      out.print(dto.getDob());
      out.write("></td>\r\n");
      out.write("				<td>Citizenship :</td>\r\n");
      out.write("				<td><select name=\"citizen\" id=\"citizen\">\r\n");
      out.write("						<option value=\"sc\"\r\n");
      out.write("							");
if (dto.getCitizen() != null && (dto.getCitizen().equalsIgnoreCase("Singapore Citizen"))) {
      out.write("\r\n");
      out.write("							selected ");
}
      out.write(">Singapore Citizen</option>\r\n");
      out.write("						<option value=\"spr\"\r\n");
      out.write("							");
if (dto.getCitizen() != null && (dto.getCitizen().equalsIgnoreCase("Singapore Permanent citizen"))) {
      out.write("\r\n");
      out.write("							selected ");
}
      out.write(">Singapore Permanent citizen</option>\r\n");
      out.write("						<option value=\"nc\"\r\n");
      out.write("							");
if (dto.getCitizen() != null && (dto.getCitizen().equalsIgnoreCase("Non citizen"))) {
      out.write("\r\n");
      out.write("							selected ");
}
      out.write(">Non citizen</option>\r\n");
      out.write("				</select></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"3\">Applicable for occupier who is a non-citizen\r\n");
      out.write("					with>=6 months visit pass</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Card Type</td>\r\n");
      out.write("				<td>:</td>\r\n");
      out.write("				<td><select name=\"cardType\" id=\"cardType\">\r\n");
      out.write("						<option value=\"svp\"\r\n");
      out.write("							");
if (dto.getCard() != null && (dto.getCard().equalsIgnoreCase("Social Visit Pass"))) {
      out.write("\r\n");
      out.write("							selected ");
}
      out.write(">Social Visit Pass</option>\r\n");
      out.write("						<option value=\"wp\"\r\n");
      out.write("							");
if (dto.getCard() != null && (dto.getCard().equalsIgnoreCase("Work Permit"))) {
      out.write("\r\n");
      out.write("							selected ");
}
      out.write(">Work Permit</option>\r\n");
      out.write("						<option value=\"ep\"\r\n");
      out.write("							");
if (dto.getCard() != null && (dto.getCard().equalsIgnoreCase("Employment Pass"))) {
      out.write("\r\n");
      out.write("							selected ");
}
      out.write(">Employment Pass</option>\r\n");
      out.write("						<option value=\"dp\"\r\n");
      out.write("							");
if (dto.getCard() != null && (dto.getCard().equalsIgnoreCase("Dependent Pass"))) {
      out.write("\r\n");
      out.write("							selected ");
}
      out.write(">Dependent Pass</option>\r\n");
      out.write("						<option value=\"sp\"\r\n");
      out.write("							");
if (dto.getCard() != null && (dto.getCard().equalsIgnoreCase("Student Pass"))) {
      out.write("\r\n");
      out.write("							selected ");
}
      out.write(">Student Pass</option>\r\n");
      out.write("				</select></td>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Date of Issue</td>\r\n");
      out.write("				<td>:</td>\r\n");
      out.write("				<td><input type=\"date\" name=\"doi\" id=\"doi\"\r\n");
      out.write("					value=");
      out.print(dto.getDoi());
      out.write("></td>\r\n");
      out.write("				<td>Expiry Date :</td>\r\n");
      out.write("				<td><input type=\"date\" name=\"expiry\" id=\"expiry\"\r\n");
      out.write("					value=");
      out.print(dto.getExpiry());
      out.write("></td>\r\n");
      out.write("				\r\n");
      out.write("			\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Card Type</td>\r\n");
      out.write("				<td>:</td>\r\n");
      out.write("				<td><select name=\"cardType\" id=\"cardType\" disabled>\r\n");
      out.write("						<option value=\"svp\">Social Visit Pass</option>\r\n");
      out.write("						<option value=\"wp\">Work Permit</option>\r\n");
      out.write("						<option value=\"ep\">Employment Pass</option>\r\n");
      out.write("						<option value=\"dp\">Dependent Pass</option>\r\n");
      out.write("						<option value=\"sp\">Student Pass</option>\r\n");
      out.write("				</select></td>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Date of Issue</td>\r\n");
      out.write("				<td>:</td>\r\n");
      out.write("				<td><input type=\"date\" name=\"doi\" id=\"doi\" disabled></td>\r\n");
      out.write("				<td>Expiry Date :</td>\r\n");
      out.write("				<td><input type=\"date\" name=\"expiry\" id=\"expiry\" disabled></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
