/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2023-06-10 04:22:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Contact Info</title>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function nextBtnClick() {\r\n");
      out.write("	alert('nextBtnClick');\r\n");
      out.write("	var isValid = chkInpData();\r\n");
      out.write("	if(isValid == true) {\r\n");
      out.write("		document.getElementById(\"contactForm\").method = \"Post\";\r\n");
      out.write("		document.getElementById(\"contactForm\").action = \"ContactController\";\r\n");
      out.write("		document.getElementById(\"contactForm\").submit();\r\n");
      out.write("	}\r\n");
      out.write("	//add for other fields\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function resetButtonClick() {\r\n");
      out.write("	alert(\"resetButtonClick\");\r\n");
      out.write("	document.getElementById(\"name\").value =\"\";\r\n");
      out.write("	document.getElementById(\"idNo\").value=\"\";\r\n");
      out.write("	document.getElementById(\"idType\").value=\"\";\r\n");
      out.write("	document.getElementById(\"telHome\").value=\"\";\r\n");
      out.write("	document.getElementById(\"telOffice\").value=\"\";\r\n");
      out.write("	document.getElementById(\"hp\").value=\"\";\r\n");
      out.write("	document.getElementById(\"fax\").value=\"\";\r\n");
      out.write("	document.getElementById(\"email\").value=\"\";\r\n");
      out.write("	//add for other fields\r\n");
      out.write("}\r\n");
      out.write("function validateEmail(email)\r\n");
      out.write("{\r\n");
      out.write("	var emailFormat=\"/^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$/\";\r\n");
      out.write("	if(email.value.match(emailFormat))\r\n");
      out.write("		{\r\n");
      out.write("		return true;\r\n");
      out.write("		}\r\n");
      out.write("	else\r\n");
      out.write("	alert(\"Enter valid email address\");\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("function chkInpData(){\r\n");
      out.write("	var isValid = true;\r\n");
      out.write("	var name = document.getElementById(\"name\").value;\r\n");
      out.write("	var idNo = document.getElementById(\"idNo\").value;\r\n");
      out.write("	var idType = document.getElementById(\"idType\").value;\r\n");
      out.write("	var telHome=document.getElementById(\"telHome\").value;\r\n");
      out.write("	var telOffice=document.getElementById(\"telOffice\").value;\r\n");
      out.write("	var hp=document.getElementById(\"hp\").value;\r\n");
      out.write("	var fax=document.getElementById(\"fax\").value;\r\n");
      out.write("	var email=document.getElementById(\"email\").value;\r\n");
      out.write("	\r\n");
      out.write("	if(name == \"\") {\r\n");
      out.write("		isValid = false;\r\n");
      out.write("		alert(\"Please enter name\");\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(isValid == true)  {\r\n");
      out.write("		if(idNo == \"\"){\r\n");
      out.write("			isValid = false;\r\n");
      out.write("			alert(\"Please enter ID Number\");\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	if(isValid == true)  {\r\n");
      out.write("		if(idType == \"\" ) {\r\n");
      out.write("			isValid = false;\r\n");
      out.write("			alert(\"Please enter ID Type\");\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("		if(isValid==true){\r\n");
      out.write("			if(telHome==\"\")\r\n");
      out.write("				{\r\n");
      out.write("				isValid=false;\r\n");
      out.write("				alert(\"Please enter valid home number \");\r\n");
      out.write("				}\r\n");
      out.write("		}\r\n");
      out.write("			if(isValid==true)\r\n");
      out.write("				{\r\n");
      out.write("				if(telOffice==\"\")\r\n");
      out.write("					{\r\n");
      out.write("					isvalid=false;\r\n");
      out.write("					alert(\"plz enter office number\");\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			if(isValid==true)\r\n");
      out.write("			{\r\n");
      out.write("			if(hp==\"\")\r\n");
      out.write("				{\r\n");
      out.write("				isvalid=false;\r\n");
      out.write("				alert(\"plz enter handphone number\");\r\n");
      out.write("				}\r\n");
      out.write("		}\r\n");
      out.write("			if(isValid==true)\r\n");
      out.write("			{\r\n");
      out.write("			if(fax==\"\")\r\n");
      out.write("				{\r\n");
      out.write("				isvalid=false;\r\n");
      out.write("				alert(\"plz enter fax number\");\r\n");
      out.write("				}\r\n");
      out.write("	}	\r\n");
      out.write("	\r\n");
      out.write("	if(isValid == true)  {\r\n");
      out.write("		if(email == \"\") {\r\n");
      out.write("			return false;\r\n");
      out.write("			alert(\"email should not be empty\");\r\n");
      out.write("		}\r\n");
      out.write("		else\r\n");
      out.write("			validateEmail(email);\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h3 align=\"center\">CONTACT INFO</h3>\r\n");
      out.write("	<form id=\"contactForm\">\r\n");
      out.write("		<table style=\"width: 40%\">\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Name</td>\r\n");
      out.write("				<td>:</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"name\" id=\"name\" maxlength=\"6\"\r\n");
      out.write("					onkeypress=\"return /[0-9a-zA-Z]/i.test(event.key)\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Id Number</td>\r\n");
      out.write("				<td>:</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"idNo\" id=\"idNo\"\r\n");
      out.write("					onkeypress=\"return /[0-9]/i.test(event.key)\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Id Type</td>\r\n");
      out.write("				<td>:</td>\r\n");
      out.write("				<td><select name=\"idType\" id=\"idType\" required>\r\n");
      out.write("						<option value=\"empty\"></option>\r\n");
      out.write("						<option value=\"uin\">UIN</option>\r\n");
      out.write("						<option value=\"fin\">FIN</option>\r\n");
      out.write("						<option value=\"ppn\">PPN</option>\r\n");
      out.write("						<option value=\"xin\">XIN</option>\r\n");
      out.write("				</select></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Telephone(Home)</td>\r\n");
      out.write("				<td>:</td>\r\n");
      out.write("				<td><input type=\"number\" name=\"telHome\" id=\"telHome\"\r\n");
      out.write("					maxlength=\"8\" onkeypress=\"return /[0-9]/i.test(event.key)\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Telephone(office)</td>\r\n");
      out.write("				<td>:</td>\r\n");
      out.write("				<td><input type=\"number\" name=\"telOffice\" id=\"telOffice\"\r\n");
      out.write("					maxlength=\"8\" onkeypress=\"return/[1-9]/i.test(event.key)\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Hand Phone</td>\r\n");
      out.write("				<td>:</td>\r\n");
      out.write("				<td><input type=\"number\" name=\"hp\" id=\"hp\" maxlength=\"8\"\r\n");
      out.write("					onkeypress=\"return/[1-9]/i.test(event.key)\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Fax</td>\r\n");
      out.write("				<td>:</td>\r\n");
      out.write("				<td><input type=\"number\" name=\"fax\" id=\"fax\" maxlength=\"8\"\r\n");
      out.write("					onkeypress=\"return/[1-9]/i.test(event.key)\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>Email Address</td>\r\n");
      out.write("				<td>:</td>\r\n");
      out.write("				<td><input type=\"email\" name=\"email\" id=\"email\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"3\" align=\"center\"><input type=\"button\"\r\n");
      out.write("					name=\"buttonAction\" value=\"Next\" onclick=\"nextBtnClick();\">\r\n");
      out.write("					<input type=\"button\" name=\"reset\" value=\"Reset\"\r\n");
      out.write("					onclick=\"resetButtonClick();\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
